### ISSUE TITLE
Great work! May we please steal it? :)

### ISSUE THREAD

**Issue by webbertakken** [kuler90/activate-unity#1]
Hi @kuler90,

Very nice and clean setup for activating Unity.
Since it's licensed MIT, are you ok with us using it for [unity-actions](https://github.com/webbertakken/unity-actions)? Currently [unity-builder](https://github.com/webbertakken/unity-builder) and [unity-test-runner](https://github.com/webbertakken/unity-test-runner) require manual setup still for free licenses, where everyone has to activate following the "Activation" documentation.

We work together under the open source community of [unity-ci](https://github.com/unity-ci), we share our [docs](http://unity-ci.com/docs) in a central place and we have a [discord](http://unity-ci.com/discord) server. Please feel free to join us, or just drop by for a chat and let us know if you're ok with us reusing some of your activation logic.

Thanks again!

**Comment by kuler90** [comment]
Hi @webbertakken,

Sure, you can copy whole license-robot.js for personal activation.

I know about unity-ci. When I needed CI for my Unity project I started from your unity-actions :). Unfortunately, then I ran into the problem of the wrong Android NDK version in unity3d docker images. After a lot of trying to fix that I decided to write my own actions ~~with blackjack and hookers~~ based on Unity Hub.

I will join to chat. My english is not very good (sorry for that), so it will be very useful for me.

**Comment by webbertakken** [comment]
Great! Thank you so much.

We have since resolved the NDK [issue](https://gitlab.com/gableroux/unity3d/-/issues/85) as we've rebuilt our new docker [images](https://github.com/Unity-CI/docker) from the ground up. The new images are used from unity-actions version v2 (still in alpha at the time of writing, see for example [builder releases](https://github.com/webbertakken/unity-builder/releases)).
